spring.application.name=dbexplorer
server.port=8080
spring.datasource.url=jdbc:oracle:thin:@//20.170.5.146:1521/ORCLCDB
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# HikariCP connection pool optimization
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.keepalive-time=60000

# Optional JPA config (useful if Hibernate/JPA used)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
